Partie 1 – Explorer les données
1) Charger les données CSV ;

In [3]:
import pandas as pd

df = pd.read_csv("../data/smart_building_raw.csv")

2) Afficher les premières lignes du dataset ;

In [4]:
df.head()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
0,1174,2025-02-13 06:00:00,B8,Entrepôt,A,23.0,40.0,851.0,26.0,138.4,Eco,Normal,Jeudi,Non
1,1275,2025-03-10 12:00:00,B7,Bureau,D,28.0,69.0,538.0,0.0,170.2,Eco,Normal,Lundi,Non
2,1493,2025-05-04 00:00:00,B5,Centre commercial,B,19.5,52.3,1198.0,64.0,149.8,Normal,Normal,Dimanche,Oui
3,1073,2025-01-19 00:00:00,B6,Université,D,20.0,58.4,1014.0,30.0,141.6,Normal,Normal,Dimanche,Non
4,1454,2025-04-24 06:00:00,B7,Bureau,D,26.8,70.5,628.0,42.0,228.3,Normal,Normal,Jeudi,Non

3) Afficher les dernières lignes du dataset ;

In [5]:
df.tail()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
502,1107,2025-01-27 12:00:00,B2,École,C,29.8,66.5,778.0,48.0,243.5,Normal,Normal,Lundi,Non
503,1271,2025-03-09 12:00:00,B3,Hôpital,B,21.1,66.3,3900.0,53.0,145.8,Eco,Alerte,Dimanche,Oui
504,1349,2025-03-29 00:00:00,B5,Centre commercial,B,21.6,61.9,959.0,33.0,100.2,Eco,Normal,Samedi,Non
505,1436,2025-04-19 18:00:00,B7,Bureau,C,21.2,54.5,1066.0,38.0,150.9,Boost,Normal,Samedi,Oui
506,1103,2025-01-26 12:00:00,B2,École,D,NaN,64.8,584.0,29.0,163.4,Normal,Panne,Dimanche,Non

4) Combien d'observations contient le dataset ?

In [ ]:
print("Nombre d'observations :", df.shape[0])

Nombre d'observations : 507
Nombre de variables : 14

In [ ]:
5) Combien de variables possède le dataset ?

In [9]:
print("Nombre de variables :", df.shape[1])

Nombre de variables : 14

6) Identifier les variables numériques ;

In [13]:
print(df.select_dtypes(include="number").columns.tolist())

['id_mesure', 'temperature', 'humidite', 'co2', 'occupation', 'consommation_kwh']

7) Identifier les variables catégorielles ;

In [15]:
df.select_dtypes(include="object").columns.tolist()

['date',
 'batiment',
 'type_batiment',
 'zone',
 'mode_climatisation',
 'etat_systeme',
 'jour_semaine',
 'alerte']

8) Identifier les dates

In [18]:
print(df.dtypes)

id_mesure               int64
date                   object
batiment               object
type_batiment          object
zone                   object
temperature           float64
humidite              float64
co2                   float64
occupation            float64
consommation_kwh      float64
mode_climatisation     object
etat_systeme           object
jour_semaine           object
alerte                 object
dtype: object

In [25]:
print(df.date)

0     2025-02-13 06:00:00
1     2025-03-10 12:00:00
2     2025-05-04 00:00:00
3     2025-01-19 00:00:00
4     2025-04-24 06:00:00
              ...
502   2025-01-27 12:00:00
503   2025-03-09 12:00:00
504   2025-03-29 00:00:00
505   2025-04-19 18:00:00
506   2025-01-26 12:00:00
Name: date, Length: 507, dtype: datetime64[ns]

9) Identifier les identifiants

In [28]:
colonnes_id = [col for col in df.columns if "id" in col.lower()]

print("Colonnes pouvant être des identifiants :", colonnes_id)

Colonnes pouvant être des identifiants : ['id_mesure', 'humidite']

0      1174
1      1275
2      1493
3      1073
4      1454
       ...
502    1107
503    1271
504    1349
505    1436
506    1103
Name: id_mesure, Length: 507, dtype: int64

10) Déterminer les statistiques : moyenne, médiane, minimum, maximum, écart-type et quartiles.

In [31]:
df.describe()

,id_mesure,date,temperature,humidite,co2,occupation,consommation_kwh
count,507.000000,502,495.000000,496.000000,500.000000,501.000000,502.000000
mean,1251.114398,2025-03-04 13:26:03.346613504,24.154141,57.864113,844.150000,44.850299,169.069323
min,1001.000000,2025-01-01 00:00:00,-30.000000,-12.000000,89.000000,-20.000000,-100.000000
25%,1125.500000,2025-02-01 01:30:00,21.600000,49.275000,623.750000,27.000000,136.875000
50%,1252.000000,2025-03-04 21:00:00,24.000000,57.550000,787.500000,46.000000,169.800000
75%,1376.500000,2025-04-04 22:30:00,26.000000,65.750000,952.000000,61.000000,202.975000
max,1500.000000,2025-05-05 18:00:00,96.000000,160.000000,6000.000000,116.000000,336.200000
std,144.782769,NaN,7.418465,16.026336,582.181386,24.949139,53.164294